source 'https://rubygems.org'

gem 'adsf'
gem 'bitters'
gem 'bourbon'
gem 'builder'
gem 'chunky_png'
gem 'coffee-script'
gem 'fileutils'
gem 'guard-nanoc'
gem 'guard-livereload'
gem 'htmlcompressor'
gem 'i18n'
gem 'image_optim' # sudo apt-get install -y advancecomp gifsicle jhead jpegoptim libjpeg-progs optipng pngcrush
gem 'kramdown'
gem 'kss'
gem 'less'
gem 'nanoc', '~> 3.6.8'
gem 'neat'
gem 'rmagick' # sudo apt-get install imagemagick libmagickcore-dev libmagickwand-dev
gem 'sass'
gem 'slim'
gem 'spriteful'
gem 'therubyracer'
gem 'uglifier'
gem 'yuicompressor', '1.3.2'
